# Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

AWSTemplateFormatVersion: 2010-09-09

Parameters:
  PipelineName:
    Type: String

  ProjectName:
    Type: String

  NotificationAddress:
    Type: String

Resources:
  CanaryRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          Effect: Allow
          Principal:
            Service: events.amazonaws.com
          Action: sts:AssumeRole
      Policies:
        - PolicyName: "canary-policy"
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Action:
                  - codepipeline:StartPipelineExecution
                Effect: Allow
                Resource:
                  - !Sub "arn:aws:codepipeline:${AWS::Region}:${AWS::AccountId}:${PipelineName}"

  DailyCodePipelineTriggerRule:
    Type: AWS::Events::Rule
    Properties:
      Description: "Trigger CodePipeline execution"
      ScheduleExpression: cron(0 13 * * ? *)
      State: ENABLED
      Targets:
        - Arn: !Sub "arn:aws:codepipeline:${AWS::Region}:${AWS::AccountId}:${PipelineName}"
          RoleArn: !GetAtt CanaryRole.Arn
          Id: "CodePipelineCanary"

  SnsCanaryTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: !Sub "${ProjectName} Canary Failure"
      TopicName: !Sub "${ProjectName}-canary-failure"

  SnsCanarySubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !Ref NotificationAddress
      Protocol: email
      TopicArn: !Ref SnsCanaryTopic

  CanaryAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmActions:
        - !Ref SnsCanaryTopic
      ComparisonOperator: LessThanThreshold
      EvaluationPeriods: 1
      MetricName: Attempts
      Namespace: !Ref ProjectName
      Period: 86400
      Statistic: Minimum
      Threshold: 1.0
      TreatMissingData: breaching

  CanaryEventTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              AWS: "*"
            Action: sns:Publish
            Resource: !Ref SnsCanaryTopic
            Condition:
              ArnEquals:
                "aws:SourceArn": !GetAtt CanaryAlarm.Arn
      Topics:
        - !Ref SnsCanaryTopic
